apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-app
  labels:
    managed-by: dso
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      application: nginx-app
  template:
    metadata:
      labels:
        application: nginx-app
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: {{ .Values.containerName }} 
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }} 
          ports:
            - name: {{ .Values.containerPort }} #http
              containerPort: {{ .Values.containerPortNumber }} #80
             
