apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-app
  labels:
    managed-by: dso
spec:
  replicas: 3
  selector:
    matchLabels:
      application: nginx-app
  template:
    metadata:
      labels:
        application: nginx-app
    spec:
      serviceAccountName: nginx-sa
      containers:
        - name: nginx
          image: us-central1-docker.pkg.dev/iron-country-417723/app-chart/my-nginx:v1
          ports:
            - name: http
              containerPort: 80
             
