apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    managed-by: dso
spec:
 selector:
    application: nginx-app
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  
