apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }} #nginx-svc
  labels:
{{- include "commonLabels" . | nindent 4 }}
spec:
  selector:
    application: nginx-app
  ports:
    - port: {{ .Values.nginxApp.containerPortNumber }}
      targetPort: http
      protocol: TCP
      name: {{ .Values.nginxApp.containerPortName }}
  
