apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }} #nginx-svc
  labels:
    managed-by: dso
spec:
  selector:
    application: nginx-app
  ports:
    - port: {{ .Values.containerPortNumber }}
      targetPort: http
      protocol: TCP
      name: {{ .Values.containerPortName }}
  
