name: Helm Chart Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Helm
        uses: gcp/setup-helm@v1
        with:
          version: 'latest'

      - name: Lint Helm chart
        run: |
          helm lint app-helm/
