name: Helm package and push to GAR

on:
  push:
    branches:
      - main 
  workflow_run:
    workflows: ["Helm Chart Linter"]
    types:
      - completed

env:
  PROJECT_ID: iron-country-417723 
  LOCATION: us-central1
  REPO: app-helm

jobs:
  package_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          token_format: "access_token"

      - name: Package Helm Chart
        run: |
          helm package app-chart/ -d ./packaged-charts

      - name: Push Helm Chart to GAR
        run: |
          export CHART=$(ls *.tgz)
          Helm push $CHART oci://${{ env.PROJECT_ID }}-${{ env.LOCATION }}/${{ env.REPO }}/$CHART
