name: Helm package and push to GAR

on:  
  workflow_run:
    workflows: ["Helm Chart Linter"]
    types:
      - completed

env:
  PROJECT_ID: iron-country-417723 
  LOCATION: us-central1
  REPO: app-chart

jobs:
  package_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
          token_format: "access_token"

      - name: Install Helm plugin
        run: |
          helm plugin install https://github.com/chartmuseum/helm-push

      - name: Package Helm Chart
        run: |
          helm package app-chart/ -d ./packaged-charts
        working-directory: ${{ github.workspace }}

      - name: Push Helm Chart to GAR
        run: |
          helm push ./packaged-charts/*.tgz 'oci://${{ env.LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}'
